# Site
author: Toshi Kamei
author_title: startup
avatar:

# URL
url: https://hexo-kame.netlify.com/

# Sidebar
widgets:
  - search
  - profile
  - recent_posts
  - tagcloud
  - archive

# Contact
contact:
  url: tolehico@gmail.com
  icon: github # font-awesome icon. e.x) fa-github

# Google tag manager
google_analytics: GTM-XXXXXX
